### ISSUE TITLE
vat problem

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/vstore#127]
I have something set wrong way

![image](https://user-images.githubusercontent.com/5429548/59611746-2eb16400-911c-11e9-8372-b0f2f18cefe9.png)

![image](https://user-images.githubusercontent.com/5429548/59611758-36710880-911c-11e9-83f3-0d063d27a7f9.png)

No VAT:
 
![image](https://user-images.githubusercontent.com/5429548/59611829-59032180-911c-11e9-8f0f-41bbd368b7fd.png)

Check VAT id is the intention, not a mistake.

**Comment by Jimmi08** [comment]
@SimSync Hi, I am sure that problem is somewhere else, but I found this while trying to find what is wrong.

customer country was "ro"  but key in map countries was "RO"
`$country =  strtoupper($country);`
$maps returned something at least, but still no tax

This fixed it:
```
$periods = $map[$country]['periods']; 
$tax_classes = array_keys($periods[0]['rates']);
```

Periods weren't 0 key anymore. Screenshot to see changed lines.
 
![image](https://user-images.githubusercontent.com/5429548/59664730-e2186800-91b1-11e9-9fca-26c6d2f83340.png)

**Comment by Jimmi08** [comment]
@SimSync there was else this problem:
```
customer country was "ro" but key in map countries was "RO"
$country = strtoupper($country);
$maps returned something at least, but still no tax
```
Are you able to confirm or I have something wrong? Thank you for the quick fix.

**Comment by SimSync** [comment]
@Jimmi08 So business country was Slovak republic and the users country was Romania?

**Comment by Jimmi08** [comment]
Yes, but it had value "ro" (small letter) and that list of EU countries has key "RO"

**Comment by SimSync** [comment]
@Jimmi08 At least with the last merged PR, this should be fixed.
I tried with business country Slovakia Republic and changed the country of my user to Romania and it returned the tax for Romania (Standard = 19%)...
The lowercase customer country should not be a problem as it is changed to upper case in the relevant methods for the lookups.
If you still have issues, could you provide some screenshots or equivalent so that i can try to find the root cause? I will than reopen this issue.
Thanks a lot for your testing and bug reporting. This is highly appreciated!

**Comment by Jimmi08** [comment]
I will create a new one. I haven't time to check the latest changes yet.
