### ISSUE TITLE
Customer table

### ISSUE THREAD

**Issue by SimSync** [e107inc/vstore#65]
@CaMer0n Do you already have the create code for the customer table somewhere?
If you, please push it once as it is currently missing.

From the customer class, i saw the column names and there are a few where i'm not sure if they are not double or should get a different name:

| field | question |
| ---- | --------- |
| cust_userid | Is this the e107 userid? If yes, should we make it like in the order table "cust_e107_user", or what i would prefer, change the fieldname in the order table to "order_userid"? |
| cust_prename | Isn't cust_firstname the same? At least Google translate says that prename and firstname are the same... |
| cust_postcode | In the order table the postcode is named zip. I would prefer to have it the same (zip). |
| cust_comments | Is it the same as cust_notes? |
| cust_assigned_to | What is this for? |
| cust_interested | What is this for? |
| cust_refcode | What is this for? |

Given, that the address data in that table is the customers invoice address, I would like to add fields for shipping address and prefered/last payment method. Do you think it is better to have single fields for address, city, zip, and so on, or would it be enough to have a single text field and save it as json data? Of course, searching for the shipping address would be get less comfortable. But is it needed and how often is this done?
And if json for the shipping would be enough, would that also be ok for the customers (invoice) address?

**Comment by CaMer0n** [comment]
hi @SimSync  ! That code was copied from another plugin I made some time ago and was never developed further into the vstore. I ended up deciding against adding the table, because an admin could add all these fields as user-extended-fields and I wanted to keep things as simple as possible in the early stages of development. 

 I haven't looked closely at how other systems store this kind of data (eg. wooCommerce) but if you think it is better to be all within the same vstore plugin (and possibly duplicated with fields in the user table) I'm okay with proceeding in that direction with a 'customer' table in vstore. It would certainly mean less 'set up time' for an admin and simple exports from a single table. 

fyi. Info about the fields above as I used them in my other plugin:  

cust_userid = e107_id
cust_prename = Mr, Mrs, Ms. etc. 
cust_postcode = zipcode
cust_comments = comments added on a'contact us' page 
cust_assigned_to = used internally to assign customer followup to a specific admininistrator. 
cust_interested = boolean flag for internal use. 
cust_refcode = generated customer code. a mix of lastname and cust_id - printed on invoice. eg #SYM000123 

For the shipping address I think the fields (city, zip etc) are rarely ever separated, so myself, I prefer the json way of storing it. (same for billing address) 

Hope this helps.
